[package]
name = "pass-maymayqah"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
rand = "0.8.5"
colored = "2.1.0"
clipboard = "0.5.0"
encryptfile = "0.1.3"
